# coding = utf-8

from django.conf.urls import patterns, url
from .views import *

urlpatterns = patterns('',
                       url(r'^$', home, name='help'),
                       url(r'^howto-faq/$', common_problem, name="howto_faq"),
                       url(r'^deliver-time-station/$',
                           delivertimestation, name="deliver-time-station"),
                       url(r'^cargo-tracking/$', cargotracking,
                           name="cargo-tracking"),
                       url(r'^get-by-yourself/$', getbyyourself,
                           name="get-by-yourself"),
                       url(r'^service-promise/$', servicepromise,
                           name="service-promise"),
                       url(r'^exchange-help/$', exchangehelp,
                           name="exchange-help"),
                       url(r'^help_solve/$', helpsolve,
                           name='help_solve'),
                       url(r'^pay-method/$', paymethod,
                           name="pay-method"),
                       url(r'^howto-register/$', howtoregister,
                           name='howto-register'),
                       url(r'^howto-order/$', howtoorder,
                           name='howto-order'),
                       url(r'^invoice-system/$', invoicesystem,
                           name='invoice-system'),
                       url(r'^refund-system/$', refundsystem,
                           name='refund-system'),
                       url(r'^shipping-charges/$', shippingcharges,
                           name='shipping-charges'),
                    #    url(r'^exchange-process/$', exchangeprocess,
                    #        name='exchange-process'),
                       url(r'^about-us/$', about_us,
                           name='about-us'),
                       url(r'^contact-us/$', contact_us,
                           name='contact-us'),
                       )
